name: e2e-tests
signing_key:
  aws_kms:
    key_configs:
      - key_id: ${AWS_KMS_KEY_1_ID}
        region: "eu-west-1"
      - key_id: ${AWS_KMS_KEY_2_ID}
        region: "eu-west-1"
      - key_id: ${AWS_KMS_KEY_3_ID}
        region: "eu-west-1"
networks:
- name: local_anvil
  chain_id: 31337
  provider_urls:
    - http://127.0.0.1:8545
  block_explorer_url: http://localhost:8545
  automatic_top_up:
    from_address: '0x33993A4F4AA617DA4558A0CFD0C39A7989B67720'
    targets:
      - "0x1C09DF15FB12656420033EB58067EC9406EF0E26"
      - "0x6F3E343161C4B905342015AD20A5C492ADFB730E"
      - "0x68333AE8A21E1F768B20DB409486BE2D569A5258"
    native:
      enabled: true
      min_balance: "50"
      top_up_amount: "100"
    erc20_tokens:
      - address: "0x99bba657f2bbc93c02d617f8ba121cb8fc104acf" # Deterministic TestToken address
        min_balance: "100"
        top_up_amount: "500"
api_config:
  port: 3000
  authentication_username: ${RRELAYER_AUTH_USERNAME}
  authentication_password: ${RRELAYER_AUTH_PASSWORD}
webhooks:
- endpoint: http://localhost:8546/webhook
  shared_secret: ${RRELAYER_WEBHOOK_SHARED_SECRET}
  networks:
  - local_anvil
# TODO: once we have 10 KMS keys
#safe_proxy:
#  - address: "0xcfe267de230a234c5937f18f239617b7038ec271" # Deterministic Safe proxy address
#    relayers:
#      - "0xa63d35C7545af0233DCF54B7f43d10dFb9E19038" # Wallet index 2 (only 3 KMS keys so AWS_KMS_KEY_3_ID)
rate_limits:
  limits:
    transactions_per_minute: 1
    signing_operations_per_minute: 1
  user_unlimited_overrides:
    - "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    - "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    - "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
    - "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"