name: e2e-tests
signing_key:
  gcp_secret_manager:
    project_id: ${GCP_PROJECT_ID}
    secret_id: ${GCP_SECRET_ID}
networks:
- name: local_anvil
  chain_id: 31337
  provider_urls:
    - http://127.0.0.1:8545
  block_explorer_url: http://localhost:8545
  automatic_top_up:
    from_address: '0x655B2B8861D7E911D283A05A5CAD042C157106DA'
    targets:
      - "0x1C09DF15FB12656420033EB58067EC9406EF0E26"
      - "0x6F3E343161C4B905342015AD20A5C492ADFB730E"
      - "0x68333AE8A21E1F768B20DB409486BE2D569A5258"
    native:
      enabled: true
      min_balance: "50"
      top_up_amount: "100"
    erc20_tokens:
      - address: "0x99bba657f2bbc93c02d617f8ba121cb8fc104acf" # Deterministic TestToken address
        min_balance: "100"
        top_up_amount: "500"
api_config:
  port: 3000
  authentication_username: ${RRELAYER_AUTH_USERNAME}
  authentication_password: ${RRELAYER_AUTH_PASSWORD}
webhooks:
- endpoint: http://localhost:8546/webhook
  shared_secret: ${RRELAYER_WEBHOOK_SHARED_SECRET}
  networks:
  - local_anvil
safe_proxy:
  - address: "0xcfe267de230a234c5937f18f239617b7038ec271" # Deterministic Safe proxy address
    relayers:
      - "0x1C073e63f70701BC545019D3c4f2a25A69eCA8Cf" # Wallet index 80
rate_limits:
  limits:
    transactions_per_minute: 1
    signing_operations_per_minute: 1
  user_unlimited_overrides:
    - "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    - "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    - "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
    - "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"