name: e2e-tests
signing_provider:
  privy:
    app_id: ${PRIVY_APP_ID}
    app_secret: ${PRIVY_APP_SECRET}
networks:
- name: local_anvil
  chain_id: 31337
  provider_urls:
    - http://127.0.0.1:8545
  block_explorer_url: http://localhost:8545
  automatic_top_up:
    from:
       # safe: "0xd9fa512bc7ec216f0c01f4de4232629f3ec3bac7" # optional
       relayer:
          address: '0xd9fa512bc7ec216f0c01f4de4232629f3ec3bac7'
          internal_only: false
    targets:
      - "0x1C09DF15FB12656420033EB58067EC9406EF0E26"
      - "0x6F3E343161C4B905342015AD20A5C492ADFB730E"
      - "0x68333AE8A21E1F768B20DB409486BE2D569A5258"
    native:
      min_balance: "50"
      top_up_amount: "100"
    erc20_tokens:
      - address: "0x99bba657f2bbc93c02d617f8ba121cb8fc104acf" # Deterministic TestToken address
        min_balance: "100"
        top_up_amount: "500"
  permissions:
    - relayers:
         - "0xd9fa512bc7ec216f0c01f4de4232629f3ec3bac7" # or *
      allowlist:
         - "0x6F3E343161C4B905342015AD20A5C492ADFB730E"
         - "0x6F3E343161C4B905342015AD20A5C492ADFB730E"
      disable_native_transfer: true
      # TODO: need to test these
      disable_personal_sign: false
      disable_typed_data_sign: false
      disable_transactions: false
api_config:
  port: 3000
  authentication_username: ${RRELAYER_AUTH_USERNAME}
  authentication_password: ${RRELAYER_AUTH_PASSWORD}
webhooks:
- endpoint: http://localhost:8546/webhook
  shared_secret: ${RRELAYER_WEBHOOK_SHARED_SECRET}
  networks:
  - local_anvil
rate_limits:
  user_limits:
    per_relayer:
      interval: "minute"
      transactions: 1
      signing_operations: 1
    global:
      interval: "minute"
      transactions: 3
      signing_operations: 3
# TODO: needs testing
#  relayer_limits:
#    interval: "minute"
#    transactions: 5
#    signing_operations: 100
