volumes:
  postgres_data:
    driver: local

services:
  postgresql:
    image: postgres:16
    shm_size: 1g
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5446:5432
    env_file:
      - .env
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U $${DATABASE_USER} -d $${DATABASE_NAME} -q']
      interval: 5s
      timeout: 10s
      retries: 10

  # app:
  #   build: .
  #   depends_on:
  #     - postgresql
  #   env_file:
  #     - ./.env
  #   ports:
  #     - '8000:8000'
