volumes:
  postgres_data:
    driver: local

services:
  postgresql:
    image: postgres:16
    platform: linux/arm64
    shm_size: 1g
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5441:5432
    env_file:
      - ./.env
